//! Short-lived, hash-indexed Asset access Grants.

use std::{
    collections::HashMap,
    sync::{Arc, Mutex},
};

use getrandom::getrandom;
use orbitrelay_core::Timestamp;
use orbitrelay_protocol::{ActorId, SessionId};
use sha2::{Digest, Sha256};
use thiserror::Error;

use orbitrelay_asset::AssetId;

/// Clock boundary used by Grant issuance and validation.
pub trait DeliveryClock: Send + Sync {
    /// Returns the current UTC timestamp.
    fn now(&self) -> Timestamp;
}

/// Production clock backed by OrbitRelay's UTC timestamp type.
#[derive(Clone, Copy, Debug, Default)]
pub struct SystemDeliveryClock;

impl DeliveryClock for SystemDeliveryClock {
    fn now(&self) -> Timestamp {
        Timestamp::now_utc()
    }
}

/// Internal immutable Grant record. Raw bearer tokens are never stored.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AssetAccessGrant {
    asset_id: AssetId,
    actor_id: ActorId,
    session_id: SessionId,
    document_id: orbitrelay_document::DocumentId,
    expires_at: Timestamp,
}

impl AssetAccessGrant {
    /// Returns the Asset bound to this Grant.
    #[must_use]
    pub const fn asset_id(&self) -> &AssetId {
        &self.asset_id
    }
    /// Returns the actor bound to this Grant.
    #[must_use]
    pub const fn actor_id(&self) -> &ActorId {
        &self.actor_id
    }
    /// Returns the Session bound to this Grant.
    #[must_use]
    pub const fn session_id(&self) -> &SessionId {
        &self.session_id
    }
    /// Returns the Document relation used to issue this Grant.
    #[must_use]
    pub const fn document_id(&self) -> &orbitrelay_document::DocumentId {
        &self.document_id
    }
    /// Returns the public expiration timestamp.
    #[must_use]
    pub const fn expires_at(&self) -> &Timestamp {
        &self.expires_at
    }
}

/// Stable Grant registry failures.
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum GrantError {
    /// The registry reached its bounded capacity.
    #[error("asset Grant registry is unavailable")]
    Unavailable,
    /// The token could not be generated by the OS random source.
    #[error("asset Grant token generation failed")]
    Randomness,
    /// The requested Grant was not valid for the requested Asset.
    #[error("asset Grant is unauthorized")]
    Unauthorized,
}

/// A bounded in-memory Grant issuer and validator.
pub struct AssetAccessGrantIssuer {
    entries: Mutex<HashMap<[u8; 32], AssetAccessGrant>>,
    ttl_seconds: i64,
    max_grants: usize,
    clock: Arc<dyn DeliveryClock>,
}

impl AssetAccessGrantIssuer {
    /// Creates a bounded issuer with an injected clock.
    #[must_use]
    pub fn new(ttl_seconds: i64, max_grants: usize, clock: Arc<dyn DeliveryClock>) -> Self {
        Self {
            entries: Mutex::new(HashMap::new()),
            ttl_seconds,
            max_grants,
            clock,
        }
    }

    /// Issues a reusable random bearer token and stores only its digest.
    pub fn issue(
        &self,
        asset_id: AssetId,
        actor_id: ActorId,
        session_id: SessionId,
        document_id: orbitrelay_document::DocumentId,
    ) -> Result<(String, AssetAccessGrant), GrantError> {
        let now = self.clock.now();
        let expires_at =
            Timestamp::from_unix_timestamp(now.unix_timestamp().saturating_add(self.ttl_seconds))
                .map_err(|_| GrantError::Unavailable)?;
        let mut entries = self
            .entries
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        entries.retain(|_, grant| grant.expires_at.unix_timestamp() > now.unix_timestamp());
        if entries.len() >= self.max_grants {
            return Err(GrantError::Unavailable);
        }

        let mut raw = [0_u8; 32];
        getrandom(&mut raw).map_err(|_| GrantError::Randomness)?;
        let token = base64url(&raw);
        let digest = digest(&raw);
        let grant = AssetAccessGrant {
            asset_id,
            actor_id,
            session_id,
            document_id,
            expires_at,
        };
        entries.insert(digest, grant.clone());
        Ok((token, grant))
    }

    /// Validates a token digest and its Asset binding without scanning entries.
    pub fn validate(
        &self,
        token: &str,
        asset_id: &AssetId,
    ) -> Result<AssetAccessGrant, GrantError> {
        if token.len() != 43 {
            return Err(GrantError::Unauthorized);
        }
        let raw = decode_base64url(token).ok_or(GrantError::Unauthorized)?;
        if raw.len() != 32 {
            return Err(GrantError::Unauthorized);
        }
        let mut bytes = [0_u8; 32];
        bytes.copy_from_slice(&raw);
        if base64url(&bytes) != token {
            return Err(GrantError::Unauthorized);
        }
        let key = digest(&bytes);
        let now = self.clock.now();
        let mut entries = self
            .entries
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        let Some(grant) = entries.get(&key).cloned() else {
            return Err(GrantError::Unauthorized);
        };
        if grant.expires_at.unix_timestamp() <= now.unix_timestamp() {
            entries.remove(&key);
            return Err(GrantError::Unauthorized);
        }
        if grant.asset_id != *asset_id {
            return Err(GrantError::Unauthorized);
        }
        Ok(grant)
    }

    /// Returns the number of active in-memory records.
    #[must_use]
    pub fn len(&self) -> usize {
        self.entries
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .len()
    }

    /// Returns whether no active Grant records are stored.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

fn digest(raw: &[u8; 32]) -> [u8; 32] {
    let result = Sha256::digest(raw);
    let mut digest = [0_u8; 32];
    digest.copy_from_slice(&result);
    digest
}

fn base64url(bytes: &[u8; 32]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    let mut output = String::with_capacity(43);
    let mut buffer = 0_u32;
    let mut bits = 0_u8;
    for byte in bytes {
        buffer = (buffer << 8) | u32::from(*byte);
        bits += 8;
        while bits >= 6 {
            bits -= 6;
            output.push(TABLE[((buffer >> bits) & 0x3f) as usize] as char);
        }
    }
    if bits > 0 {
        output.push(TABLE[((buffer << (6 - bits)) & 0x3f) as usize] as char);
    }
    output
}

fn decode_base64url(value: &str) -> Option<Vec<u8>> {
    if value.is_empty() || value.contains('=') {
        return None;
    }
    let mut output = Vec::with_capacity(value.len() * 3 / 4);
    let mut buffer = 0_u32;
    let mut bits = 0_u8;
    for byte in value.bytes() {
        let value = match byte {
            b'A'..=b'Z' => byte - b'A',
            b'a'..=b'z' => byte - b'a' + 26,
            b'0'..=b'9' => byte - b'0' + 52,
            b'-' => 62,
            b'_' => 63,
            _ => return None,
        };
        buffer = (buffer << 6) | u32::from(value);
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            output.push(((buffer >> bits) & 0xff) as u8);
        }
    }
    Some(output)
}

#[cfg(test)]
mod tests {
    use std::sync::{Arc, Mutex};

    use orbitrelay_asset::AssetId;
    use orbitrelay_core::Timestamp;
    use orbitrelay_document::DocumentId;
    use orbitrelay_protocol::{ActorId, SessionId};

    use super::{AssetAccessGrantIssuer, DeliveryClock, GrantError};

    struct TestClock(Mutex<i64>);

    impl DeliveryClock for TestClock {
        fn now(&self) -> Timestamp {
            Timestamp::from_unix_timestamp(*self.0.lock().expect("clock lock")).expect("timestamp")
        }
    }

    fn issuer(clock: Arc<TestClock>, max_grants: usize) -> AssetAccessGrantIssuer {
        AssetAccessGrantIssuer::new(600, max_grants, clock)
    }

    #[test]
    fn tokens_are_opaque_reusable_and_asset_bound() {
        let clock = Arc::new(TestClock(Mutex::new(1_700_000_000)));
        let issuer = issuer(clock, 4);
        let asset = AssetId::new();
        let (token, grant) = issuer
            .issue(
                asset.clone(),
                ActorId::new(),
                SessionId::new(),
                DocumentId::new(),
            )
            .expect("Grant");
        assert_eq!(token.len(), 43);
        assert!(!token.contains(&asset.to_string()));
        assert_eq!(
            issuer.validate(&token, &asset).expect("valid").asset_id(),
            &asset
        );
        assert!(matches!(
            issuer.validate(&token, &AssetId::new()),
            Err(GrantError::Unauthorized)
        ));
        assert_eq!(grant.expires_at().unix_timestamp(), 1_700_000_600);
        assert_eq!(issuer.len(), 1);
    }

    #[test]
    fn expiry_and_capacity_are_bounded_without_full_scan_on_validation() {
        let clock = Arc::new(TestClock(Mutex::new(1_700_000_000)));
        let issuer = issuer(Arc::clone(&clock), 1);
        issuer
            .issue(
                AssetId::new(),
                ActorId::new(),
                SessionId::new(),
                DocumentId::new(),
            )
            .expect("first Grant");
        assert!(matches!(
            issuer.issue(
                AssetId::new(),
                ActorId::new(),
                SessionId::new(),
                DocumentId::new()
            ),
            Err(GrantError::Unavailable)
        ));
        *clock.0.lock().expect("clock lock") = 1_700_000_601;
        issuer
            .issue(
                AssetId::new(),
                ActorId::new(),
                SessionId::new(),
                DocumentId::new(),
            )
            .expect("expired entry should be cleaned");
    }
}
